import './globals.css'
import AuthProvider from './components/authProvider/authProvider'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <AuthProvider>
        <div className='wrapper'>
          <main>
           {children}
          </main>
        
        </div>
        </AuthProvider>
      </body>
    </html>
  )
}
